import Employee1 from "../src/Assets/AdminAvatar1.avif";
import Employee2 from "../src/Assets/AdminAvatar2.avif";
import Employee3 from "../src/Assets/AdminAvatar3.avif";
import Employee4 from "../src/Assets/AdminAvatar4.avif";
import Employee5 from "../src/Assets/AdminAvatar5.avif";
import Employee6 from "../src/Assets/AdminAvatar6.avif";
import Employee7 from "../src/Assets/AdminAvatar7.avif";
import Employee8 from "../src/Assets/AdminAvatar8.avif";
import Employee9 from "../src/Assets/AdminAvatar9.avif";
import Employee10 from "../src/Assets/AdminAvatar10.avif";
import Employee11 from "../src/Assets/AdminAvatar11.avif";
import Employee12 from "../src/Assets/AdminAvatar12.avif";
import Employee13 from "../src/Assets/AdminAvatar13.avif";
import Employee14 from "../src/Assets/AdminAvatar14.avif";
import Employee15 from "../src/Assets/AdminAvatar15.avif";
import Employee16 from "../src/Assets/AdminAvatar16.avif";
import Employee17 from "../src/Assets/AdminAvatar17.avif";
import Employee18 from "../src/Assets/AdminAvatar18.avif";
import Employee19 from "../src/Assets/AdminAvatar19.avif";
import Employee20 from "../src/Assets/AdminAvatar20.avif";
import Employee21 from "../src/Assets/AdminAvatar21.avif";

export const Taskss = [];

export const Employees = [
  {
    id: 1,
    fullname: "Sadie Matthews",
    role: "Web Designer",
    Email: "Sadie@hotmail.com",
    linkedin: "",
    instagram: "",
    github: "",
    employeeID: "#100",
    address: "1400 pooh Bear lane",
    phone: "001-002-003",
    profileImg: Employee1,
    country: "USA",
    Age: "22",
    Salary: "$2,000",
    Education: "Degree",
    rating: 3,
    condition: false,
  },
  {
    id: 2,
    fullname: "Korbin Kirby",
    role: "Web Developer",
    Email: "Korbin@hotmail.com",
    linkedin: "http://www.linkedin.com/in/soolainang",
    instagram: "https://www.instagram.com/_____soolaiman.g/",
    github: "https://github.com/SoolaimanG",
    employeeID: "#200",
    address: "1400 SpongeBob lane",
    phone: "010-026-263",
    profileImg: Employee2,
    country: "KSA",
    Age: 32,
    Salary: "$3,000",
    Education: "Degree",
    rating: 4,
    condition: false,
  },
  {
    id: 3,
    fullname: "Kash Herring",
    role: "Software Engineer",
    Email: "Kash@hotmail.com",
    linkedin: "http://www.linkedin.com/in/soolainang",
    instagram: "https://www.instagram.com/_____soolaiman.g/",
    github: "https://github.com/SoolaimanG",
    employeeID: "#300",
    address: "1400 Pawpaw lane",
    phone: "110-096-210",
    profileImg: Employee3,
    country: "USA",
    Age: 19,
    Salary: "$4,500",
    Education: null,
    rating: 3.5,
    condition: false,
  },
  {
    id: 4,
    fullname: "Isaias Rose",
    role: "Software Engineer",
    Email: "Rose@hotmail.com",
    linkedin: "http://www.linkedin.com/in/soolainang",
    instagram: "https://www.instagram.com/_____soolaiman.g/",
    github: "https://github.com/SoolaimanG",
    employeeID: "#400",
    address: "1400 Ikoyi lane",
    phone: "234-0962-210",
    profileImg: Employee4,
    country: "Nigeria",
    Age: 35,
    Salary: "$1,500",
    Education: "Degree",
    rating: 2,
    condition: false,
  },
  {
    id: 5,
    fullname: "Logan Atkinson",
    role: "Google Analytics",
    Email: "Logan@hotmail.com",
    linkedin: "http://www.linkedin.com/in/soolainang",
    instagram: "https://www.instagram.com/_____soolaiman.g/",
    github: "https://github.com/SoolaimanG",
    employeeID: "#500",
    address: "1400 Mickey lane",
    phone: "234-0962-210",
    profileImg: Employee5,
    country: "China",
    Age: 21,
    Salary: "$2,100",
    Education: "Degree",
    rating: 4.2,
    condition: false,
  },
  {
    id: 6,
    fullname: "Jordan Hancock",
    role: "Cyber Security",
    Email: "Jordan@hotmail.com",
    linkedin: "http://www.linkedin.com/in/soolainang",
    instagram: "https://www.instagram.com/_____soolaiman.g/",
    github: "https://github.com/SoolaimanG",
    employeeID: "#600",
    address: "1400 Banny lane",
    phone: "102-062-290",
    profileImg: Employee6,
    country: "USA",
    Age: 21,
    Salary: "$3,900",
    Education: "PHD",
    rating: 4.8,
    condition: false,
  },
  {
    id: 7,
    fullname: "Santiago Bailey",
    role: "Web Developer",
    Email: "Santiago@hotmail.com",
    linkedin: "http://www.linkedin.com/in/soolainang",
    instagram: "https://www.instagram.com/_____soolaiman.g/",
    github: "https://github.com/SoolaimanG",
    employeeID: "#700",
    address: "1400 Ben lane",
    phone: "126-096-210",
    profileImg: Employee7,
    country: "Spain",
    Age: 24,
    Salary: "$1,900",
    Education: "Degree",
    rating: 2.9,
    condition: false,
  },
  {
    id: 8,
    fullname: "Bentley Chen",
    role: "Product Manager",
    Email: "Chen@hotmail.com",
    linkedin: "http://www.linkedin.com/in/soolainang",
    instagram: "https://www.instagram.com/_____soolaiman.g/",
    github: "https://github.com/SoolaimanG",
    employeeID: "#800",
    address: "1400 Sophia lane",
    phone: "126-096-210",
    profileImg: Employee8,
    country: "China",
    Age: 22,
    Salary: "$1,900",
    Education: null,
    rating: 2.9,
    condition: false,
  },
  {
    id: 9,
    fullname: "Bentley Chen",
    role: "Product Manager",
    Email: "Chen@hotmail.com",
    linkedin: "http://www.linkedin.com/in/soolainang",
    instagram: "https://www.instagram.com/_____soolaiman.g/",
    github: "https://github.com/SoolaimanG",
    employeeID: "#900",
    address: "1400 Tom lane",
    phone: "106-096-410",
    profileImg: Employee9,
    country: "USA",
    Age: 54,
    Salary: "$10,000",
    Education: "PHD",
    rating: 5,
    condition: false,
  },
  {
    id: 10,
    fullname: "Eva Haynes",
    role: "Social Media Manager",
    Email: "Eva@hotmail.com",
    linkedin: "http://www.linkedin.com/in/soolainang",
    instagram: "https://www.instagram.com/_____soolaiman.g/",
    github: "https://github.com/SoolaimanG",
    employeeID: "#1000",
    address: "1400 Jerry lane",
    phone: "301-096-500",
    profileImg: Employee10,
    country: "Colombia",
    Age: 41,
    Salary: "$5,000",
    Education: "PHD",
    rating: 4,
    condition: false,
  },
  {
    id: 11,
    fullname: "Ashtyn Dean",
    role: "Cyber Security",
    Email: "Dean@hotmail.com",
    linkedin: "http://www.linkedin.com/in/soolainang",
    instagram: "https://www.instagram.com/_____soolaiman.g/",
    github: "https://github.com/SoolaimanG",
    employeeID: "#1100",
    address: "1400 Jerry lane",
    phone: "301-096-500",
    profileImg: Employee11,
    country: "Nigeria",
    Age: 25,
    Salary: "$3,000",
    Education: null,
    rating: 3.9,
    condition: false,
  },
  {
    id: 12,
    fullname: "Sammir Hanna",
    role: "Google Analytic",
    Email: "Hanna@hotmail.com",
    linkedin: "http://www.linkedin.com/in/soolainang",
    instagram: "https://www.instagram.com/_____soolaiman.g/",
    github: "https://github.com/SoolaimanG",
    employeeID: "#1200",
    address: "1400 Dwarf lane",
    phone: "301-966-500",
    profileImg: Employee12,
    country: "Ghana",
    Age: 35,
    Salary: "$3,100",
    Education: "Degree",
    rating: 3,
    condition: false,
  },
  {
    id: 13,
    fullname: "Malaki May",
    role: "Social Media Manager",
    Email: "May@hotmail.com",
    linkedin: "http://www.linkedin.com/in/soolainang",
    instagram: "https://www.instagram.com/_____soolaiman.g/",
    github: "https://github.com/SoolaimanG",
    employeeID: "#1300",
    address: "1400 Snow lane",
    phone: "901-096-500",
    profileImg: Employee13,
    country: "Russia",
    Age: 29,
    Salary: "$4,300",
    Education: "Degree",
    rating: 3.6,
    condition: false,
  },
  {
    id: 14,
    fullname: "Samir Shephard",
    role: "Product Manager",
    Email: "Samir@hotmail.com",
    linkedin: "http://www.linkedin.com/in/soolainang",
    instagram: "https://www.instagram.com/_____soolaiman.g/",
    github: "https://github.com/SoolaimanG",
    employeeID: "#1400",
    address: "1400 Rick lane",
    phone: "150-096-500",
    profileImg: Employee14,
    country: "Spain",
    Age: 39,
    Salary: "$10,000",
    Education: "PHD",
    rating: 4.9,
    condition: false,
  },
  {
    id: 15,
    fullname: "Jayden Otega",
    role: "Software Engineer",
    Email: "Otega@hotmail.com",
    linkedin: "http://www.linkedin.com/in/soolainang",
    instagram: "https://www.instagram.com/_____soolaiman.g/",
    github: "https://github.com/SoolaimanG",
    employeeID: "#1500",
    address: "1400 Morty lane",
    phone: "811-096-500",
    profileImg: Employee15,
    country: "London",
    Age: 32,
    Salary: "$1,000",
    Education: null,
    rating: 2.3,
    condition: false,
  },
  {
    id: 16,
    fullname: "Adrienne Pitts",
    role: "Product Manager",
    Email: "Pitts@hotmail.com",
    linkedin: "http://www.linkedin.com/in/soolainang",
    instagram: "https://www.instagram.com/_____soolaiman.g/",
    github: "https://github.com/SoolaimanG",
    employeeID: "#1600",
    address: "1400 Zuma lane",
    phone: "301-096-700",
    profileImg: Employee16,
    country: "Nigeria",
    Age: 18,
    Salary: "$5,000",
    Education: "PHD",
    rating: 3.5,
    condition: false,
  },
  {
    id: 17,
    fullname: "Emilliano Harmon",
    role: "Technical",
    Email: "Eva@hotmail.com",
    linkedin: "http://www.linkedin.com/in/soolainang",
    instagram: "https://www.instagram.com/_____soolaiman.g/",
    github: "https://github.com/SoolaimanG",
    employeeID: "#1000",
    address: "1400 Jerry lane",
    phone: "301-096-500",
    profileImg: Employee17,
    country: "USA",
    Age: 38,
    Salary: "$5,000",
    Education: "PHD",
    rating: 4,
    condition: false,
  },
  {
    id: 18,
    fullname: "Cale Padilla",
    role: "Web Developer",
    Email: "Cale@hotmail.com",
    linkedin: "http://www.linkedin.com/in/soolainang",
    instagram: "https://www.instagram.com/_____soolaiman.g/",
    github: "https://github.com/SoolaimanG",
    employeeID: "#1800",
    address: "1400 Shaun lane",
    phone: "301-096-500",
    profileImg: Employee18,
    country: "Nigeria",
    Age: 18,
    Salary: "$5,000",
    Education: "Degree",
    rating: 4.6,
    condition: false,
  },
  {
    id: 19,
    fullname: "Francesca Rangel",
    role: "Entertainment",
    Email: "Rangel@hotmail.com",
    linkedin: "http://www.linkedin.com/in/soolainang",
    instagram: "https://www.instagram.com/_____soolaiman.g/",
    github: "https://github.com/SoolaimanG",
    employeeID: "#1900",
    address: "1400 Jerry lane",
    phone: "301-096-500",
    profileImg: Employee19,
    country: "Cameroon",
    Age: 19,
    Salary: "$1,000",
    Education: "Degree",
    rating: 3.1,
    condition: false,
  },
  {
    id: 20,
    fullname: "Joy Lee",
    role: "Social Media Manager",
    Email: "Lee@hotmail.com",
    linkedin: "http://www.linkedin.com/in/soolainang",
    instagram: "https://www.instagram.com/_____soolaiman.g/",
    github: "https://github.com/SoolaimanG",
    employeeID: "#2000",
    address: "1400 Ghost lane",
    phone: "001-096-300",
    profileImg: Employee20,
    country: "Morroco",
    Age: 20,
    Salary: "$5,000",
    Education: "PHD",
    rating: 4,
    condition: false,
  },
  {
    id: 21,
    fullname: "Draven Riddle",
    role: "Graphics",
    Email: "Eva@hotmail.com",
    linkedin: "http://www.linkedin.com/in/soolainang",
    instagram: "https://www.instagram.com/_____soolaiman.g/",
    github: "https://github.com/SoolaimanG",
    employeeID: "#2100",
    address: "1400 Spider lane",
    phone: "011-016-500",
    profileImg: Employee21,
    country: "Zambia",
    Age: 21,
    Salary: "$3,000",
    Education: "Degree",
    rating: 2.7,
    condition: false,
  },
];

export const Product = [
  {
    id: 1,
    ProductName: "Nike Air Max",
    ProductDescription:
      "Sleek black running shoe with breathable mesh upper and comfortable foam midsole",
    ProductImage:
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8bWVucyUyMHNob2V8ZW58MHx8MHx8&auto=format&fit=crop&w=600&q=60",
    ProductPrice: 40,
    ProductStock: true,
    ProductCategory: "Shoe",
    ProductQuantity: "10",
    ProductStatus: true,
    ProductRating: 3,
    ProductCondition: false,
    ProductCreatedAt: 2022,
  },
  {
    id: 2,
    ProductName: "Adidas Ultraboost",
    ProductDescription:
      "Stylish white running shoe with responsive Boost cushioning and flexible knit upper",
    ProductImage:
      "https://images.unsplash.com/photo-1608231387042-66d1773070a5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8bWVucyUyMHNob2V8ZW58MHx8MHx8&auto=format&fit=crop&w=600&q=60",
    ProductPrice: 120,
    ProductStock: true,
    ProductCategory: "Shoe",
    ProductQuantity: "5",
    ProductStatus: true,
    ProductRating: 4.5,
    ProductCondition: false,
    ProductCreatedAt: 2021,
  },
  {
    id: 3,
    ProductName: "Adidas Ultraboost",
    ProductDescription:
      "Lightweight running shoe with a responsive boost midsole and breathable knit upper",
    ProductImage:
      "https://images.unsplash.com/photo-1560769629-975ec94e6a86?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8bWVucyUyMHNob2V8ZW58MHx8MHx8&auto=format&fit=crop&w=600&q=60",
    ProductPrice: 50,
    ProductStock: true,
    ProductCategory: "Shoe",
    ProductQuantity: "15",
    ProductStatus: true,
    ProductRating: 4,
    ProductCondition: true,
    ProductCreatedAt: 2021,
  },
  {
    id: 4,
    ProductName: "Puma Calibrate",
    ProductDescription:
      "Modern running shoe with energy-returning foam midsole and breathable upper",
    ProductImage:
      "https://images.unsplash.com/photo-1608667508764-33cf0726b13a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8bWVucyUyMHNob2V8ZW58MHx8MHx8&auto=format&fit=crop&w=600&q=60",
    ProductPrice: 45,
    ProductStock: true,
    ProductCategory: "Shoe",
    ProductQuantity: "8",
    ProductStatus: true,
    ProductRating: 4,
    ProductCondition: true,
    ProductCreatedAt: 2021,
  },
  {
    id: 5,
    ProductName: "Under Armour HOVR",
    ProductDescription:
      "Lightweight running shoe with cushioned HOVR foam and supportive heel counter",
    ProductImage:
      "https://images.unsplash.com/photo-1512374382149-233c42b6a83b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8bWVucyUyMHNob2V8ZW58MHx8MHx8&auto=format&fit=crop&w=600&q=60",
    ProductPrice: 55,
    ProductStock: true,
    ProductCategory: "Shoe",
    ProductQuantity: "12",
    ProductStatus: true,
    ProductRating: 4,
    ProductCondition: true,
    ProductCreatedAt: 2020,
  },
  {
    id: 6,
    ProductName: "New Balance Fresh Foam",
    ProductDescription:
      "Neutral running shoe with Fresh Foam midsole and breathable mesh upper",
    ProductImage:
      "https://images.unsplash.com/photo-1539185441755-769473a23570?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTJ8fG1lbnMlMjBzaG9lfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=600&q=60",
    ProductPrice: 50,
    ProductStock: true,
    ProductCategory: "Shoe",
    ProductQuantity: "9",
    ProductStatus: true,
    ProductRating: 4,
    ProductCondition: true,
    ProductCreatedAt: 2020,
  },
  {
    id: 7,
    ProductName: "Brooks Ghost",
    ProductDescription:
      "Cushioned running shoe with responsive DNA Loft foam and breathable upper",
    ProductImage:
      "https://images.unsplash.com/photo-1491553895911-0055eca6402d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTh8fG1lbnMlMjBzaG9lfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=600&q=60",
    ProductPrice: 60,
    ProductStock: true,
    ProductCategory: "Shoe",
    ProductQuantity: "10",
    ProductStatus: true,
    ProductRating: 5,
    ProductCondition: true,
    ProductCreatedAt: 2019,
  },
  {
    id: 8,
    ProductName: "Mizuno Wave Rider",
    ProductDescription:
      "Neutral running shoe with Wave Plate technology for stability and cushioning",
    ProductImage:
      "https://images.unsplash.com/photo-1549298916-b41d501d3772?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTR8fG1lbnMlMjBzaG9lfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=600&q=60",
    ProductPrice: 55,
    ProductStock: true,
    ProductCategory: "Shoe",
    ProductQuantity: "7",
    ProductStatus: true,
    ProductRating: 4,
    ProductCondition: true,
    ProductCreatedAt: 2019,
  },
  {
    id: 9,
    ProductName: "Saucony Kinvara",
    ProductDescription:
      "Lightweight running shoe with responsive foam midsole and breathable upper",
    ProductImage:
      "https://images.unsplash.com/photo-1515955656352-a1fa3ffcd111?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTV8fG1lbnMlMjBzaG9lfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=600&q=60",
    ProductPrice: 50,
    ProductStock: true,
    ProductCategory: "Shoe",
    ProductQuantity: "8",
    ProductStatus: true,
    ProductRating: 4,
    ProductCondition: true,
    ProductCreatedAt: 2018,
  },
  {
    id: 10,
    ProductName: "Hoka One One Clifton",
    ProductDescription:
      "Cushioned running shoe with lightweight foam and breathable mesh upper",
    ProductImage:
      "https://images.unsplash.com/photo-1616696038562-574c18066055?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjB8fG1lbnMlMjBzaG9lfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=600&q=60",
    ProductPrice: 65,
    ProductStock: true,
    ProductRating: 4,
    ProductCategory: "Shoe",
    ProductQuantity: "6",
    ProductStatus: true,
  },
  {
    id: 20,
    ProductName: "Nike Air Zoom Pegasus 38",
    ProductDescription:
      "Lightweight running shoe with responsive foam and breathable upper",
    ProductImage:
      "https://images.unsplash.com/photo-1518894781321-630e638d0742?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzJ8fG1lbnMlMjBzaG9lfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=600&q=60",
    ProductPrice: 90,
    ProductRating: 4,
    ProductStock: true,
    ProductCategory: "Shoe",
    ProductQuantity: 8,
    ProductStatus: true,
    ProductCondition: true,
  },
  {
    id: 11,
    ProductName: "Levi's 501 Original Fit Jeans",
    ProductDescription: "Classic straight leg jeans made with durable denim",
    ProductImage:
      "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTh8fG1lbnMlMjBjbG90aGVzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=600&q=60",
    ProductPrice: 50,
    ProductStock: true,
    ProductCategory: "Clothing",
    ProductRating: 4,
    ProductQuantity: 10,
    ProductStatus: true,
    ProductCondition: true,
  },
  {
    id: 12,
    ProductName: "Lee Men's Regular Fit Straight Leg Jeans",
    ProductDescription: "Classic straight leg jeans made with durable denim",
    ProductImage:
      "https://images.unsplash.com/photo-1611312449408-fcece27cdbb7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTJ8fG1lbnMlMjBjbG90aGVzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=600&q=60",
    ProductPrice: 40,
    ProductRating: 4,
    ProductStock: true,
    ProductCategory: "Clothing",
    ProductQuantity: 8,
    ProductStatus: true,
    ProductCondition: true,
  },
  {
    id: 13,
    ProductName: "Lucky Brand Men's 181 Relaxed Straight Leg Jeans",
    ProductDescription:
      "Relaxed fit straight leg jeans made with high-quality denim",
    ProductImage:
      "https://images.unsplash.com/photo-1611312449297-a69dc9c3987b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjR8fG1lbnMlMjBjbG90aGVzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=600&q=60",
    ProductPrice: 70,
    ProductRating: 4.5,
    ProductStock: true,
    ProductCategory: "Clothing",
    ProductQuantity: 6,
    ProductStatus: true,
    ProductCondition: true,
  },
  {
    id: 14,
    ProductName: "Calvin Klein Men's Straight Fit Jeans",
    ProductDescription:
      "Classic straight leg jeans made with high-quality denim",
    ProductImage:
      "https://images.unsplash.com/photo-1564584217132-2271feaeb3c5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mzl8fG1lbnMlMjBjbG90aGVzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=600&q=60",
    ProductPrice: 60,
    ProductRating: 4.5,
    ProductStock: true,
    ProductCategory: "Clothing",
    ProductQuantity: 10,
    ProductStatus: true,
    ProductCondition: true,
  },
  {
    id: 15,
    ProductName: "GAP Men's Straight Fit Jeans",
    ProductDescription: "Classic straight leg jeans made with durable denim",
    ProductImage:
      "https://images.unsplash.com/photo-1523381294911-8d3cead13475?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nzh8fG1lbnMlMjBjbG90aGVzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=600&q=60",
    ProductPrice: 45,
    ProductRating: 4,
    ProductStock: true,
    ProductCategory: "Clothing",
    ProductQuantity: 14,
    ProductStatus: true,
    ProductCondition: true,
  },
  {
    id: 16,
    ProductName: "Tommy Hilfiger Men's Original Straight Fit Jeans",
    ProductDescription:
      "Classic straight leg jeans made with high-quality denim",
    ProductImage:
      "https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nzl8fG1lbnMlMjBjbG90aGVzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=600&q=60",
    ProductPrice: 80,
    ProductRating: 4.5,
    ProductStock: true,
    ProductCategory: "Clothing",
    ProductQuantity: 5,
    ProductStatus: true,
    ProductCondition: true,
  },
  {
    id: 17,
    ProductName: "J.Crew Mercantile Men's Straight Fit Jeans",
    ProductDescription: "Classic straight leg jeans made with durable denim",
    ProductImage:
      "https://images.unsplash.com/photo-1611312449545-94176309c857?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTEwfHxtZW5zJTIwY2xvdGhlc3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=600&q=60",
    ProductPrice: 38,
    ProductRating: 4,
    ProductStock: true,
    ProductCategory: "Clothing",
    ProductQuantity: 9,
    ProductStatus: true,
    ProductCondition: true,
  },
  {
    id: 18,
    ProductName: "Levi's 501 Original Fit Men's Jeans",
    ProductDescription:
      "The classic straight leg jeans made with durable denim that has a unique, timeless look",
    ProductImage:
      "https://images.unsplash.com/photo-1562157873-818bc0726f68?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTE1fHxtZW5zJTIwY2xvdGhlc3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=600&q=60",
    ProductPrice: 60,
    productRating: 4.5,
    ProductStock: true,
    ProductCategory: "Clothing",
    ProductQuantity: 12,
    ProductStatus: true,
    productCondition: true,
  },
  {
    id: 19,
    ProductName: "Nike Air Max 270 React Women's Shoes",
    ProductDescription: "Comfortable and stylish shoes with a unique colorway",
    ProductImage:
      "https://images.unsplash.com/photo-1499971442178-8c10fdf5f6ac?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTI4fHxtZW5zJTIwY2xvdGhlc3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=600&q=60",
    ProductPrice: 150,
    productRating: 4.8,
    ProductStock: true,
    ProductCategory: "Shoes",
    ProductQuantity: 8,
    ProductStatus: true,
    productCondition: "New",
  },
];

export const usersss = [
  {
    id: 1,
    name: "John Smith",
    email: "johnsmith@example.com",
    age: 35,
    phone: "555-555-1234",
    company: "Acme Corporation",
    income: 100000,
    imageUrl:
      "https://cdn.pixabay.com/photo/2013/07/13/10/07/man-156584__340.png",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    age: 28,
    phone: "555-555-5678",
    company: "XYZ Inc.",
    income: 75000,
    imageUrl:
      "https://www.pngall.com/wp-content/uploads/12/Avatar-Profile-Vector-PNG-File.png",
  },
  {
    id: 3,
    name: "Robert Lee",
    email: "rlee@example.com",
    age: 43,
    phone: "555-555-9012",
    company: "Lee Industries",
    income: 125000,
    imageUrl:
      "https://cdn3.iconfinder.com/data/icons/avatars-15/64/_Ninja-2-512.png",
  },
  {
    id: 4,
    name: "Emily Chen",
    email: "echen@example.com",
    age: 31,
    phone: "555-555-3456",
    company: "Chen Enterprises",
    income: 90000,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgpmagAEnb-i1KxV4FBuH_dDAtfwqY5JfH6Q&usqp=CAU",
  },
  {
    id: 5,
    name: "David Kim",
    email: "dkim@example.com",
    age: 27,
    phone: "555-555-7890",
    company: "Kim Co.",
    income: 60000,
    imageUrl:
      "https://whatsondisneyplus.com/wp-content/uploads/2022/03/moon-knight-avatar.png",
  },
  {
    id: 6,
    name: "Samantha Jones",
    email: "sjones@example.com",
    age: 39,
    phone: "555-555-2345",
    company: "Jones Corp.",
    income: 110000,
    imageUrl:
      "https://avatoon.me/wp-content/uploads/2021/09/Cartoon-Pic-Ideas-for-DP-Profile-10.png",
  },
  {
    id: 7,
    name: "Adam Patel",
    email: "apatel@example.com",
    age: 33,
    phone: "555-555-6789",
    company: "Patel Enterprises",
    income: 80000,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5yTxBxqX7UPLILheEuZbgOuYver2PQLQxuQ&usqp=CAU",
  },
  {
    id: 8,
    name: "Karen Johnson",
    email: "kjohnson@example.com",
    age: 45,
    phone: "555-555-1234",
    company: "Johnson & Sons",
    income: 135000,
    imageUrl:
      "https://png.pngtree.com/png-vector/20220709/ourmid/pngtree-businessman-user-avatar-wearing-suit-with-red-tie-png-image_5809521.png",
  },
  {
    id: 9,
    name: "Andrew Lee",
    email: "alee@example.com",
    age: 29,
    phone: "555-555-5678",
    company: "Lee Enterprises",
    income: 65000,
    imageUrl:
      "https://static.vecteezy.com/system/resources/thumbnails/017/225/482/small/businessman-avatar-profile-icon-male-face-with-office-suit-and-tie-illustration-vector.jpg",
  },
  {
    id: 10,
    name: "Jennifer Chen",
    email: "jchen@example.com",
    age: 37,
    phone: "555-555-9012",
    company: "Chen Corp.",
    income: 95000,
    imageUrl:
      "https://media.istockphoto.com/id/1356420393/photo/3d-futuristic-woman-with-metaverse-vr-glasses.jpg?b=1&s=170667a&w=0&k=20&c=UTCXG8WzdGTrm4JOVan7Q8WbizJ-oSWW1GMvtvhNEpY=",
  },
  {
    id: 11,
    name: "Michael Nguyen",
    email: "mnguyen@example.com",
    age: 42,
    phone: "555-555-3456",
    company: "Nguyen Industries",
    income: 120000,
    imageUrl: "https://example.com/profile11.jpg",
  },
  {
    id: 12,
    name: "Ashley Kim",
    email: "akim@example.com",
    age: 25,
    phone: "555-555-7890",
    company: "Kim Enterprises",
    income: 55000,
    imageUrl:
      "https://media.istockphoto.com/id/1433039224/photo/blue-user-3d-icon-person-profile-concept-isolated-on-white-background-with-social-member.jpg?b=1&s=170667a&w=0&k=20&c=X-ZNF80_ASKvWpbOICHC8Pf27CFCRyh7Ce9SDVopjZg=",
  },
  {
    id: 13,
    name: "Daniel Park",
    email: "dpark@example.com",
    age: 36,
    phone: "555-555-2345",
    company: "Park Co.",
    income: 100000,
    imageUrl:
      "https://media.istockphoto.com/id/1358330778/photo/deep-learning-artificial-intelligence-abstract-background.jpg?b=1&s=170667a&w=0&k=20&c=7vt3pBX-GPX9wbuywQRvsNxcMkm8eWRjbWtaO5rXtb0=",
  },
  {
    id: 14,
    name: "Elizabeth Davis",
    email: "edavis@example.com",
    age: 31,
    phone: "555-555-6789",
    company: "Davis Enterprises",
    income: 75000,
    imageUrl:
      "https://media.istockphoto.com/id/1364105164/photo/hologram-human-head-deep-learning-and-artificial-intelligence-abstract-background.jpg?b=1&s=170667a&w=0&k=20&c=i9-oulHCR0LCxqzqUW2Q7bKt3RrdbCZU0OXqXV2gw-o=",
  },
  {
    id: 15,
    name: "Ryan Martinez",
    email: "rmartinez@example.com",
    age: 29,
    phone: "555-555-1234",
    company: "Martinez Inc.",
    income: 65000,
    imageUrl:
      "https://media.istockphoto.com/id/1401980646/photo/3d-rendered-classic-sculpture-metaverse-avatar-with-network-of-low-poly-glowing-purple-lines.jpg?b=1&s=170667a&w=0&k=20&c=nLf9fDcHVLZ9bPijP5QQrj0apVLdPXITVF6EAMqj1rg=",
  },
  {
    id: 16,
    name: "Amanda Brown",
    email: "abrown@example.com",
    age: 27,
    phone: "555-555-5678",
    company: "Brown Co.",
    income: 60000,
    imageUrl:
      "https://media.istockphoto.com/id/1369826066/photo/blue-female-cyber-with-neon-pink-meta-verse-loading-text-goggles-on-geometric-dark-background.jpg?b=1&s=170667a&w=0&k=20&c=fqBwVtHkU2q68tdfEfRtd-knDhgUPZeW9OXcM0LVL5U=",
  },
  {
    id: 17,
    name: "William Wong",
    email: "wwong@example.com",
    age: 38,
    phone: "555-555-9012",
    company: "Wong Industries",
    income: 90000,
    imageUrl:
      "https://www.pngmart.com/files/21/Account-Avatar-Profile-PNG-Photo.png",
  },
  {
    id: 18,
    name: "Jessica Lee",
    email: "jlee@example.com",
    age: 26,
    phone: "555-555-3456",
    company: "Lee Corp.",
    income: 55000,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgxpLyp8g617m3Jan7xXXw3rMVCMxJLs0CGw&usqp=CAU",
  },
  {
    id: 19,
    name: "Brandon Chen",
    email: "bchen@example.com",
    age: 30,
    phone: "555-555-7890",
    company: "Chen & Associates",
    income: 80000,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSA26XphCUrK5Miap7R1oX7VxxiqmPKDcGq5w&usqp=CAU",
  },
  {
    id: 20,
    name: "Melissa Nguyen",
    email: "mnguyen@example.com",
    age: 34,
    phone: "555-555-2345",
    company: "Nguyen Corp.",
    income: 95000,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAiloZATTeBvnoqXymBGz9LW-bQkWBVpNYoA&usqp=CAU",
  },
];
